disabled_rules:
    - cyclomatic_complexity
    - trailing_whitespace

analyzer_rules:
    - unused_import

opt_in_rules:
    - array_init
    - closing_brace
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - colon # promote to error
    - convenience_type
    - contains_over_first_not_nil
    - duplicate_imports
    - empty_collection_literal
    - empty_count
    - empty_string
    - enum_case_associated_values_count
    - fatal_error_message
    - first_where
    - for_where
    - force_cast
    - force_try
    - force_unwrapping
    - identifier_name
    - implicitly_unwrapped_optional
    - indentation_width
    - last_where
    - legacy_random
    - literal_expression_end_indentation
    - multiline_arguments
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - operator_usage_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - prefer_self_type_over_type_of_self
    - redundant_nil_coalescing
    - redundant_type_annotation
    - strict_fileprivate
    - sorted_first_last
    - todo
    - toggle_bool
    - unneeded_parentheses_in_closure_argument
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - yoda_condition

force_unwrapping: error

file_length:
    warning: 600
    error: 1000

large_tuple:
    warning: 4
    error: 8

line_length:
    warning: 200
    error: 300

function_body_length:
    warning: 100
    error: 200

type_body_length:
    warning: 300
    error: 500

identifier_name:
    min_length:
        warning: 2

indentation_width:
    include_comments: false

type_name:
    min_length: 2
    max_length:
        warning: 80
        error: 100

function_parameter_count:
    warning: 8
    error: 10

identifier_name:
  excluded: ["x", "y", "z", "n", "id"]

